version: '3'

services:
  neo4j:
    image: neo4j:4.4.8-community
    environment:
      NEO4J_AUTH: neo4j/database_password
    networks:
      - neo4j
    ports:
      - '9000:7687'
      - '9001:7474'

networks:
  neo4j:
    driver: bridge
